#####
#    d_ball.R
#    - Record the effects of an increasing
#      number (d) of features when data points
#      follow a uniform distribution over the
#      unit cube having vertices {+-1}^d.
#####

#' - volume of a d-dimensional ball of radius r
#'
#' @param d <int> dimension
#' @param r <dbl> radius
#' @param check_d <lgl> validate args
#'
#' @return volume of a d-dimensional ball of radius r
#' @export
vol_d_ball <- function(
    d = 1L, # <int> dimension
    r = 1,  # <dbl> radius
    check_d = FALSE # <lgl> validate args
) {
  if (check_d) {
    assertthat::assert_that(
      d >= 1,
      r >  0)
  }

  # case where r = 1
  vol_1 <- ( pi ^ (d/2) ) / gamma( (d + 2)/2 )

  return( vol_1 * r^d )
}

#' - area of the surface of a d-dimensional ball of radius r
#'
#' - i.e., area of a sphere of local dimension (d - 1)
#'
#' @param d <int> dimension
#' @param r <dbl> radius
#' @param check_d <lgl> validate args
#'
#' @return surface area of a d-dimensional ball of radius r
#' @export
surf_d_ball <- function(
    d = 1L, # <int> dimension
    r = 1,  # <dbl> radius
    check_d = FALSE # <lgl> validate args
) {
  if (check_d) {
    assertthat::assert_that(
      d >= 1,
      r >  0)
  }

  # case where r = 1
  surf_1 <- 2 * ( pi ^ (d/2) ) / gamma( d/2 )

  return( surf_1 * r^(d - 1L) )
}

#' - volume of a d-dimensional cube of radius r
#'
#' - i.e., a cube having edge-length (2 * r)
#' - that envelopes the tangent d-ball
#'
#' @param d <int> dimension
#' @param r <dbl> radius
#' @param check_d <lgl> validate args
#'
#' @return volume of a d-dimensional cube of radius r
#' @export
vol_d_cube <- function(
    d = 1L, # <int> dimension
    r = 1,  # <dbl> radius
    check_d = FALSE # <lgl> validate args
) {
  if (check_d) {
    assertthat::assert_that(
      d >= 1,
      r >  0)
  }

  return( (2 * r)^d )
}

#' - diameter of a d-dimensional cube of radius r
#'
#' - i.e., a cube having edge-length (2 * r)
#' - that envelopes the tangent d-ball
#'
#' @param d <int> dimension
#' @param r <dbl> radius
#' @param check_d <lgl> validate args
#'
#' @return diameter of a d-dimensional cube of radius r
#' @export
diam_d_cube <- function(
    d = 1L, # <int> dimension
    r = 1,  # <dbl> radius
    check_d = FALSE # <lgl> validate args
) {
  if (check_d) {
    assertthat::assert_that(
      d >= 1,
      r >  0)
  }

  return( 2 * r * sqrt(d) )
}

#' - volume of cube divided by
#'
#' - volume of inscribed ball
#'
#' @param d <int> dimension
#' @param check_d <lgl> validate args
#'
#' @return volume ratio, cube / (inscribed ball)
#' @export
ratio_vol_cube_ball <- function(
    d       = 1L,   # <int> dimension
    check_d = FALSE # <lgl> validate args
) {
  if (check_d) {
    assertthat::assert_that( d >= 1 )
  }

  # v(cube) / v(ball)
  v_cb <- d * 2^(d - 1L) * gamma( d/2 ) / pi^(d/2)

  return( v_cb )
}

#' - Asymptotic (mean, variance, sd) of:
#'
#' - the norm of a random d-vector X
#' generated by a uniform distribution
#' over r * the unit cube
#'
#' @param d <int> dimension
#' @param r <dbl> radius
#' @param check_d <lgl> validate args
#'
#' @return norm of a uniform random d-vector
#' @export
uc_norm_stats <- function(
    d       = 1L,   # <int> dimension
    r       = 1,    # <dbl> radius
    check_d = FALSE # <lgl> validate args
) {
  if (check_d) {
    assertthat::assert_that(
      d >= 1,
      r >  0)
  }

  # stats for U^2, where U ~ uniform over interval (0, 1)
  u2_mean <- 1/3
  u2_var  <- 4/45
  u2_sd   <- sqrt(u2_var)

  ##
  #  set Z = X/r ~ uniform over the unit cube
  ##

  # norm(Z), asymptotic expected value
  z_norm2_mean <- d * u2_mean
  z_norm_mean  <- sqrt(z_norm2_mean)

  # norm(Z), asymptotic variance and sd
  z_norm2_var <- d * u2_var
  z_norm_var  <- 1/135
  z_norm_sd   <- sqrt(z_norm_var)

  ##
  #  scale by r
  ##

  return(list(
    x_norm_mean = r   * z_norm_mean,
    x_norm_var  = r^2 * z_norm_var,
    x_norm_sd   = r   * z_norm_sd
  ))
}


##
#  EOF
##
