# R/get_core_packages.R

#' Core packages for EDA for ML student projects
#'
#' Returns the vector of packages loaded in the setup chunk of every
#' `chNN-work.qmd` generated by [create_project()].
#'
#' @return Character vector of package names.
#' @keywords internal
get_core_packages <- function() {
  c("eda4mlr", "here", "knitr", "tidyverse")
}
